// Shared product catalog — single source of truth for the grid and the
// per-product SEO pages. Edit product data here.

export interface CatalogProduct {
  name: string;
  description: string;
  price: string;
  originalPrice: string;
  features: string[];
  popular: boolean;
  image: string;
  badge?: string;
}

export type CatalogCategory =
  | "bundles" | "windows" | "office" | "server" | "visio"
  | "project" | "sql" | "visualstudio" | "antivirus";

export const catalog: Record<CatalogCategory, CatalogProduct[]> = {
    bundles: [
      {
        name: "Windows 11 Pro + Office 2021 Pro Plus Bundle",
        description: "Genuine Windows 11 Pro and Office 2021 Pro Plus together — one bundle, one low price",
        price: "$59.99",
        originalPrice: "$639.98",
        features: ["Windows 11 Pro License", "Office 2021 Pro Plus License", "Lifetime · 1 PC", "Instant Delivery", "Word, Excel, PowerPoint, Outlook & more"],
        popular: true,
        image: "",
        badge: "Best Value",
      },
      {
        name: "Windows 10 Pro + Office 2021 Pro Plus Bundle",
        description: "Genuine Windows 10 Pro paired with Office 2021 Pro Plus at a bundle price",
        price: "$52.99",
        originalPrice: "$589.98",
        features: ["Windows 10 Pro License", "Office 2021 Pro Plus License", "Lifetime · 1 PC", "Instant Delivery", "Full Office app suite"],
        popular: false,
        image: "",
        badge: "Bundle",
      },
    ],
    windows: [
      {
        name: "Windows 11 Pro",
        description: "Latest Windows OS with professional features",
        price: "$39.99",
        originalPrice: "$199.99",
        features: ["Lifetime License", "1 PC", "Instant Delivery", "Remote Desktop", "BitLocker Encryption"],
        popular: true,
        image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 11 Pro - Online Key",
        description: "Digital activation via Microsoft servers",
        price: "$33",
        originalPrice: "$199.99",
        features: ["Online Activation", "1 PC", "Instant Delivery", "Digital License", "Microsoft Account Bind"],
        popular: false,
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Windows 11 Pro - Phone Key",
        description: "Telephone activation for offline PCs",
        price: "$42",
        originalPrice: "$199.99",
        features: ["Phone Activation", "1 PC", "Instant Delivery", "Offline Activation", "No Internet Required"],
        popular: false,
        image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&h=600&fit=crop&q=80",
        badge: "Phone",
      },
      {
        name: "Windows 11 Home",
        description: "Perfect for home users and students",
        price: "$32.99",
        originalPrice: "$139.99",
        features: ["Lifetime License", "1 PC", "Instant Delivery", "Gaming Optimized", "Security Updates"],
        popular: false,
        image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 10 Pro",
        description: "Stable and reliable professional OS",
        price: "$31",
        originalPrice: "$199.99",
        features: ["Lifetime License", "1 PC", "Instant Delivery", "Tested & Trusted", "Long-term Support"],
        popular: false,
        image: "https://images.unsplash.com/photo-1593642532400-2682810df593?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 10 Pro - Online Key",
        description: "Digital activation with Microsoft account",
        price: "$29.99",
        originalPrice: "$199.99",
        features: ["Online Activation", "1 PC", "Instant Delivery", "Cloud Linked", "Easy Reinstall"],
        popular: false,
        image: "https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Windows 10 Pro - Phone Key",
        description: "Reliable phone activation method",
        price: "$36",
        originalPrice: "$199.99",
        features: ["Phone Activation", "1 PC", "Instant Delivery", "Works Offline", "100% Genuine"],
        popular: false,
        image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop&q=80",
        badge: "Phone",
      },
      {
        name: "Windows 10 Home",
        description: "Classic Windows experience",
        price: "$27.99",
        originalPrice: "$139.99",
        features: ["Lifetime License", "1 PC", "Instant Delivery", "Stable Performance", "Regular Updates"],
        popular: false,
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 8.1 Pro",
        description: "Efficient OS for older hardware",
        price: "$25",
        originalPrice: "$199.99",
        features: ["Lifetime License", "1 PC", "Instant Delivery", "Lightweight", "Legacy Support"],
        popular: false,
        image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 7 Professional",
        description: "Classic Windows 7 for legacy systems",
        price: "$24.99",
        originalPrice: "$199.99",
        features: ["Lifetime License", "1 PC", "Instant Delivery", "Legacy Software Support", "Stable & Tested"],
        popular: false,
        image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 365 Business (1 Month)",
        description: "Cloud PC streaming service from Microsoft",
        price: "$47",
        originalPrice: "",
        features: ["Cloud PC", "Windows 11", "Access from Any Device", "2 vCPU, 4GB RAM, 128GB Storage", "1 Month Subscription"],
        popular: false,
        image: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 11 Enterprise",
        description: "Advanced security and management features",
        price: "$46.99",
        originalPrice: "$309.00",
        features: ["Lifetime License", "1 PC", "Advanced Security", "Device Guard", "Credential Guard"],
        popular: false,
        image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 10 Enterprise",
        description: "Enterprise-grade Windows for businesses",
        price: "$41",
        originalPrice: "$309.00",
        features: ["Lifetime License", "1 PC", "Advanced Security", "DirectAccess", "AppLocker"],
        popular: false,
        image: "https://images.unsplash.com/photo-1593642532400-2682810df593?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows 11 Pro for Workstations",
        description: "High-performance OS for advanced workloads",
        price: "$45.99",
        originalPrice: "$309.00",
        features: ["Lifetime License", "1 PC", "ReFS File System", "Up to 6TB RAM", "Server-grade Performance"],
        popular: false,
        image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&h=600&fit=crop&q=80",
      },
    ],
    office: [
      {
        name: "Office 2021 Professional Plus",
        description: "Complete Office suite with all applications",
        price: "$49.99",
        originalPrice: "$439.99",
        features: ["Word, Excel, PowerPoint", "Outlook, Access, Publisher", "Lifetime License", "1 PC", "Instant Delivery"],
        popular: true,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Office 2021 Pro Plus - Online Key",
        description: "Digital activation via Microsoft account",
        price: "$43",
        originalPrice: "$439.99",
        features: ["All Office Apps", "Online Activation", "Lifetime License", "1 PC", "Cloud Integration"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Office 2021 Pro Plus - Bind Key",
        description: "Bound to Microsoft account permanently",
        price: "$47.99",
        originalPrice: "$439.99",
        features: ["All Office Apps", "Account Bind", "Lifetime License", "1 PC", "Easy Transfer"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
        badge: "Bind",
      },
      {
        name: "Office 2021 Pro Plus - Phone Key",
        description: "Phone activation for offline use",
        price: "$52",
        originalPrice: "$439.99",
        features: ["All Office Apps", "Phone Activation", "Lifetime License", "1 PC", "Offline Ready"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
        badge: "Phone",
      },
      {
        name: "Office 2021 Home & Business",
        description: "Essential Office apps for home and business",
        price: "$44.99",
        originalPrice: "$249.99",
        features: ["Word, Excel, PowerPoint", "Outlook", "Lifetime License", "1 PC/Mac", "Instant Delivery"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Office 2019 Professional Plus",
        description: "Reliable Office 2019 suite",
        price: "$42",
        originalPrice: "$439.99",
        features: ["Word, Excel, PowerPoint", "Outlook, Access, Publisher", "Lifetime License", "1 PC", "Proven Stability"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Office 2019 Pro Plus - Online Key",
        description: "Digital version of Office 2019",
        price: "$41.99",
        originalPrice: "$439.99",
        features: ["All Office Apps", "Online Activation", "Lifetime License", "1 PC", "Quick Setup"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Office 2019 Pro Plus - Bind Key",
        description: "Account-bound Office 2019",
        price: "$46",
        originalPrice: "$439.99",
        features: ["All Office Apps", "Account Bind", "Lifetime License", "1 PC", "Secure"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
        badge: "Bind",
      },
      {
        name: "Office 2019 Pro Plus - Phone Key",
        description: "Traditional activation method",
        price: "$43.99",
        originalPrice: "$439.99",
        features: ["All Office Apps", "Phone Activation", "Lifetime License", "1 PC", "100% Working"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
        badge: "Phone",
      },
      {
        name: "Office 2016 Professional Plus",
        description: "Proven Office suite for professionals",
        price: "$37",
        originalPrice: "$439.99",
        features: ["Word, Excel, PowerPoint", "Outlook, Access, Publisher", "Lifetime License", "1 PC", "Trusted Version"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Office 2013 Professional Plus",
        description: "Classic Office suite for legacy systems",
        price: "$34.99",
        originalPrice: "$399.99",
        features: ["Word, Excel, PowerPoint", "Outlook, Access, Publisher", "Lifetime License", "1 PC", "Legacy Support"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Office 365 (1 Year)",
        description: "Cloud-based Office with 1TB OneDrive",
        price: "$57",
        originalPrice: "$99.99",
        features: ["All Office Apps", "1TB OneDrive", "5 Devices", "1 Year Subscription", "Always Updated"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Microsoft 365 Business Standard (1 Year)",
        description: "Complete business productivity suite",
        price: "$79.99",
        originalPrice: "$144.00",
        features: ["All Office Apps", "1TB OneDrive", "Microsoft Teams", "Business Email", "1 Year Subscription"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Office 2010 Professional Plus",
        description: "Legacy Office suite for older systems",
        price: "$33",
        originalPrice: "$499.99",
        features: ["Word, Excel, PowerPoint", "Outlook, Access, Publisher", "Lifetime License", "1 PC", "Legacy Support"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Office Home & Student 2021",
        description: "Perfect for students and home use",
        price: "$38.99",
        originalPrice: "$149.99",
        features: ["Word, Excel, PowerPoint", "OneNote", "Lifetime License", "1 PC/Mac", "No Outlook"],
        popular: false,
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&q=80",
      },
    ],
    server: [
      {
        name: "Windows Server 2022 Standard",
        description: "Enterprise-grade server operating system",
        price: "$69.99",
        originalPrice: "$1,069.00",
        features: ["2 VMs", "Hyper-V", "Storage Replica", "Lifetime License", "Instant Delivery"],
        popular: true,
        image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows Server 2022 Standard - Online Key",
        description: "Digital activation for Server 2022",
        price: "$64",
        originalPrice: "$1,069.00",
        features: ["2 VMs", "Online Activation", "Hyper-V", "Lifetime License", "Quick Setup"],
        popular: false,
        image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Windows Server 2019 Standard",
        description: "Reliable server platform",
        price: "$62.99",
        originalPrice: "$972.00",
        features: ["2 VMs", "Hyper-V", "Containers", "Lifetime License", "Tested & Trusted"],
        popular: false,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows Server 2019 Standard - Online Key",
        description: "Online activation Server 2019",
        price: "$58",
        originalPrice: "$972.00",
        features: ["2 VMs", "Online Activation", "Hyper-V", "Lifetime License", "Instant Setup"],
        popular: false,
        image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Windows Server 2022 Datacenter",
        description: "Unlimited virtualization rights",
        price: "$99.99",
        originalPrice: "$6,155.00",
        features: ["Unlimited VMs", "Shielded VMs", "Storage Spaces Direct", "Lifetime License", "Enterprise Features"],
        popular: false,
        image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows Server 2016 Standard",
        description: "Proven server solution",
        price: "$57",
        originalPrice: "$882.00",
        features: ["2 VMs", "Hyper-V", "Nano Server", "Lifetime License", "Stable Release"],
        popular: false,
        image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows Server 2019 Datacenter",
        description: "Unlimited virtualization for data centers",
        price: "$94.99",
        originalPrice: "$6,155.00",
        features: ["Unlimited VMs", "Hyper-V", "Storage Spaces Direct", "Lifetime License", "Enterprise Scale"],
        popular: false,
        image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows Server 2016 Datacenter",
        description: "Legacy datacenter edition",
        price: "$88",
        originalPrice: "$6,155.00",
        features: ["Unlimited VMs", "Hyper-V", "Software Defined Datacenter", "Lifetime License", "Proven Stable"],
        popular: false,
        image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows Server 2012 R2 Standard",
        description: "Reliable legacy server platform",
        price: "$53.99",
        originalPrice: "$882.00",
        features: ["2 VMs", "Hyper-V", "Storage Spaces", "Lifetime License", "Legacy Support"],
        popular: false,
        image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows Server CAL 2022 (5 Device)",
        description: "Client Access Licenses for Server 2022",
        price: "$48",
        originalPrice: "$191.00",
        features: ["5 Device CALs", "Server 2022 Compatible", "Network Access Rights", "Lifetime License", "Instant Delivery"],
        popular: false,
        image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Windows Server RDS CAL 2022 (5 User)",
        description: "Remote Desktop Services CALs",
        price: "$54.99",
        originalPrice: "$215.00",
        features: ["5 User RDS CALs", "Remote Access", "Terminal Services", "Lifetime License", "Quick Activation"],
        popular: false,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      },
    ],
    visio: [
      {
        name: "Visio Professional 2021",
        description: "Advanced diagramming and vector graphics",
        price: "$54.99",
        originalPrice: "$579.99",
        features: ["All Visio Features", "Data Visualization", "Lifetime License", "1 PC", "Instant Delivery"],
        popular: true,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visio Professional 2021 - Online Key",
        description: "Digital activation for Visio 2021",
        price: "$49",
        originalPrice: "$579.99",
        features: ["All Visio Features", "Online Activation", "Lifetime License", "1 PC", "Cloud Ready"],
        popular: false,
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Visio Professional 2021 - Phone Key",
        description: "Phone activation for offline use",
        price: "$56.99",
        originalPrice: "$579.99",
        features: ["All Visio Features", "Phone Activation", "Lifetime License", "1 PC", "Offline Ready"],
        popular: false,
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop&q=80",
        badge: "Phone",
      },
      {
        name: "Visio Standard 2021",
        description: "Essential diagramming tool",
        price: "$47",
        originalPrice: "$309.99",
        features: ["Standard Templates", "Basic Shapes", "Lifetime License", "1 PC", "Instant Delivery"],
        popular: false,
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visio Professional 2019",
        description: "Reliable diagramming solution",
        price: "$48.99",
        originalPrice: "$579.99",
        features: ["All Visio Features", "Professional Templates", "Lifetime License", "1 PC", "Proven Version"],
        popular: false,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visio Professional 2019 - Online Key",
        description: "Online activation Visio 2019",
        price: "$46",
        originalPrice: "$579.99",
        features: ["All Visio Features", "Online Activation", "Lifetime License", "1 PC", "Quick Setup"],
        popular: false,
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Visio Standard 2019",
        description: "Essential diagramming for 2019",
        price: "$42.99",
        originalPrice: "$309.99",
        features: ["Standard Templates", "Basic Shapes", "Lifetime License", "1 PC", "Reliable Version"],
        popular: false,
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visio Professional 2016",
        description: "Proven diagramming tool",
        price: "$47",
        originalPrice: "$579.99",
        features: ["All Visio Features", "Professional Templates", "Lifetime License", "1 PC", "Tested & Stable"],
        popular: false,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      },
    ],
    project: [
      {
        name: "Project Professional 2021",
        description: "Complete project management solution",
        price: "$54.99",
        originalPrice: "$1,029.99",
        features: ["Resource Management", "Team Collaboration", "Lifetime License", "1 PC", "Instant Delivery"],
        popular: true,
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Project Professional 2021 - Online Key",
        description: "Digital activation for Project 2021",
        price: "$51",
        originalPrice: "$1,029.99",
        features: ["All Project Features", "Online Activation", "Lifetime License", "1 PC", "Cloud Integration"],
        popular: false,
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Project Professional 2021 - Phone Key",
        description: "Phone activation for offline use",
        price: "$57.99",
        originalPrice: "$1,029.99",
        features: ["All Project Features", "Phone Activation", "Lifetime License", "1 PC", "Works Offline"],
        popular: false,
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop&q=80",
        badge: "Phone",
      },
      {
        name: "Project Standard 2021",
        description: "Essential project management",
        price: "$48",
        originalPrice: "$679.99",
        features: ["Task Management", "Gantt Charts", "Lifetime License", "1 PC", "Instant Delivery"],
        popular: false,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Project Professional 2019",
        description: "Reliable project management tool",
        price: "$49.99",
        originalPrice: "$1,029.99",
        features: ["Resource Management", "Portfolio Analysis", "Lifetime License", "1 PC", "Proven Stable"],
        popular: false,
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Project Professional 2019 - Online Key",
        description: "Online activation Project 2019",
        price: "$47",
        originalPrice: "$1,029.99",
        features: ["All Project Features", "Online Activation", "Lifetime License", "1 PC", "Quick Setup"],
        popular: false,
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "Project Standard 2019",
        description: "Essential project management for 2019",
        price: "$43.99",
        originalPrice: "$679.99",
        features: ["Task Management", "Gantt Charts", "Lifetime License", "1 PC", "Reliable"],
        popular: false,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Project Professional 2016",
        description: "Proven project management software",
        price: "$46",
        originalPrice: "$1,029.99",
        features: ["Resource Management", "Portfolio Analysis", "Lifetime License", "1 PC", "Stable & Tested"],
        popular: false,
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop&q=80",
      },
    ],
    sql: [
      {
        name: "SQL Server 2022 Standard",
        description: "Enterprise database management system",
        price: "$109.99",
        originalPrice: "$3,717.00",
        features: ["Core-based Licensing", "Advanced Security", "High Availability", "Lifetime License", "Instant Delivery"],
        popular: true,
        image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "SQL Server 2022 Standard - Online Key",
        description: "Digital activation for SQL 2022",
        price: "$104",
        originalPrice: "$3,717.00",
        features: ["Online Activation", "Advanced Security", "High Availability", "Lifetime License", "Cloud Ready"],
        popular: false,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "SQL Server 2019 Standard",
        description: "Proven database platform",
        price: "$99.99",
        originalPrice: "$3,717.00",
        features: ["Core-based Licensing", "Big Data Clusters", "Security Features", "Lifetime License", "Reliable"],
        popular: false,
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "SQL Server 2019 Standard - Online Key",
        description: "Online activation SQL 2019",
        price: "$96",
        originalPrice: "$3,717.00",
        features: ["Online Activation", "Big Data Support", "Security Features", "Lifetime License", "Quick Setup"],
        popular: false,
        image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=600&fit=crop&q=80",
        badge: "Online",
      },
      {
        name: "SQL Server 2017 Standard",
        description: "Stable database solution",
        price: "$93.99",
        originalPrice: "$3,717.00",
        features: ["Core-based Licensing", "Graph Data", "Machine Learning", "Lifetime License", "Proven Stable"],
        popular: false,
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "SQL Server 2022 Enterprise",
        description: "Ultimate database platform for mission-critical workloads",
        price: "$169.99",
        originalPrice: "$14,256.00",
        features: ["Unlimited Cores", "In-Memory OLTP", "Advanced Analytics", "Lifetime License", "Enterprise Grade"],
        popular: false,
        image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "SQL Server 2019 Enterprise",
        description: "High-performance enterprise database",
        price: "$159.99",
        originalPrice: "$14,256.00",
        features: ["Unlimited Cores", "Big Data Clusters", "Advanced Security", "Lifetime License", "Mission Critical"],
        popular: false,
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "SQL Server 2016 Standard",
        description: "Reliable database for business applications",
        price: "$92",
        originalPrice: "$3,717.00",
        features: ["Core-based Licensing", "In-Memory Tables", "Always Encrypted", "Lifetime License", "Proven Platform"],
        popular: false,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      },
    ],
    visualstudio: [
      {
        name: "Visual Studio 2022 Professional",
        description: "Professional IDE for developers",
        price: "$59.99",
        originalPrice: "$499.00",
        features: ["Lifetime License", "1 PC", "Advanced Debugging", "Code Refactoring", "Azure DevOps"],
        popular: true,
        image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visual Studio 2022 Enterprise",
        description: "Complete toolset for enterprise teams",
        price: "$99.99",
        originalPrice: "$5,999.00",
        features: ["Lifetime License", "1 PC", "IntelliTrace", "Code Map", "Live Unit Testing"],
        popular: false,
        image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visual Studio 2019 Professional",
        description: "Reliable IDE with proven stability",
        price: "$53",
        originalPrice: "$499.00",
        features: ["Lifetime License", "1 PC", "Multi-language Support", "Git Integration", "Team Collaboration"],
        popular: false,
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visual Studio Code Extensions Pack",
        description: "Premium extensions bundle for VS Code",
        price: "$27.99",
        originalPrice: "$49.99",
        features: ["Premium Themes", "Advanced Debugging", "AI Assistance", "Cloud Sync", "Priority Support"],
        popular: false,
        image: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visual Studio 2019 Enterprise",
        description: "Full-featured enterprise IDE",
        price: "$94.99",
        originalPrice: "$5,999.00",
        features: ["Lifetime License", "1 PC", "IntelliTrace", "Code Map", "Architecture Tools"],
        popular: false,
        image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Visual Studio 2017 Professional",
        description: "Stable IDE for professional developers",
        price: "$47",
        originalPrice: "$499.00",
        features: ["Lifetime License", "1 PC", "Code Analysis", "Testing Tools", "Cross-platform Development"],
        popular: false,
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop&q=80",
      },
    ],
    antivirus: [
      {
        name: "Kaspersky Total Security",
        description: "Complete protection for all your devices",
        price: "$38.99",
        originalPrice: "$79.99",
        features: ["3 Devices", "1 Year", "Anti-virus & Anti-malware", "VPN Included", "Parental Controls"],
        popular: true,
        image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Norton 360 Deluxe",
        description: "Advanced security with privacy features",
        price: "$44.99",
        originalPrice: "$104.99",
        features: ["5 Devices", "1 Year", "50GB Cloud Backup", "VPN Unlimited", "Dark Web Monitoring"],
        popular: false,
        image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Bitdefender Total Security",
        description: "Award-winning antivirus protection",
        price: "$37",
        originalPrice: "$89.99",
        features: ["5 Devices", "1 Year", "Multi-layer Ransomware Protection", "VPN Included", "PC Optimization"],
        popular: false,
        image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "McAfee Total Protection",
        description: "Comprehensive security suite",
        price: "$39.99",
        originalPrice: "$84.99",
        features: ["Unlimited Devices", "1 Year", "Web Protection", "Password Manager", "Identity Theft Protection"],
        popular: false,
        image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "ESET Internet Security",
        description: "Fast and light antivirus protection",
        price: "$36",
        originalPrice: "$69.99",
        features: ["3 Devices", "1 Year", "Anti-Phishing", "Banking Protection", "Anti-Theft"],
        popular: false,
        image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Avast Premium Security",
        description: "Advanced threat detection and protection",
        price: "$32.99",
        originalPrice: "$69.99",
        features: ["10 Devices", "1 Year", "Ransomware Shield", "Firewall", "Sandbox Protection"],
        popular: false,
        image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&h=600&fit=crop&q=80",
      },
      {
        name: "Trend Micro Maximum Security",
        description: "Multi-device protection suite",
        price: "$42",
        originalPrice: "$89.95",
        features: ["5 Devices", "1 Year", "Pay Guard", "Folder Shield", "Social Media Privacy"],
        popular: false,
        image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&h=600&fit=crop&q=80",
      },
    ],
};

export const categoryLabel: Record<CatalogCategory, string> = {
  bundles: "Bundles",
  windows: "Windows",
  office: "Office",
  server: "Windows Server",
  visio: "Visio & Project",
  project: "Project",
  sql: "SQL Server",
  visualstudio: "Visual Studio",
  antivirus: "Security",
};

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export interface FlatProduct extends CatalogProduct {
  category: CatalogCategory;
  slug: string;
}

export const allProducts: FlatProduct[] = (
  Object.entries(catalog) as [CatalogCategory, CatalogProduct[]][]
).flatMap(([category, list]) =>
  list.map((p) => ({ ...p, category, slug: slugify(p.name) }))
);

export function getProductBySlug(slug: string): FlatProduct | undefined {
  return allProducts.find((p) => p.slug === slug);
}

// Activation-method variants ("- Online Key", "- Phone Key", "- Bind Key") are
// the same product as their base and read as duplicates to Google. We point
// each variant's canonical at its base product so Google consolidates them
// instead of picking its own canonical ("Duplicate, Google chose different
// canonical than user").
const VARIANT_SUFFIX = /\s*-\s*(online|phone|bind)\s*key$/i;

function baseName(name: string): string {
  return name.replace(VARIANT_SUFFIX, "").trim();
}

export function canonicalSlugFor(p: FlatProduct): string {
  if (!VARIANT_SUFFIX.test(p.name)) return p.slug;
  const base = baseName(p.name);
  // "Pro Plus" and "Professional Plus" name the same edition (Office).
  const norm = (s: string) => s.toLowerCase().replace(/pro plus/g, "professional plus").trim();
  const match =
    allProducts.find((x) => x.name === base) ||
    allProducts.find((x) => !VARIANT_SUFFIX.test(x.name) && norm(x.name) === norm(base));
  return match ? match.slug : p.slug;
}

// Canonical products only (variants folded into their base) — use this for the
// sitemap so it never lists non-canonical duplicate URLs.
export const canonicalProducts: FlatProduct[] = allProducts.filter(
  (p) => canonicalSlugFor(p) === p.slug
);
